### ISSUE TITLE
Reasoning behind Caporal

### ISSUE THREAD

**Issue by jaridmargolin** [mattallty/Caporal.js#10]
It would be great to see documentation on why this was developed and how it differs from existing libraries such as [yargs](https://github.com/yargs/yargs).

**Comment by mattallty** [comment]
Hi, didn't know yargs - seems like it provide a *lot* (more) features. Was playing with commander, argv, optimist / minimist until now, but wasn't fully satisfied with them (mainly about logging, verbosity control, shell completion), so I built this. Main inspiration comes from commander for the API simplicity and Symfony Console which I was used to work with and really enjoyed.
