### ISSUE TITLE
Add ability to hide a command from the help text

### ISSUE THREAD

**Issue by fabiospampinato** [mattallty/Caporal.js#102]
It's useful to have the ability to hide some commands from the `help` text, maybe they are supported but just for development and shouldn't be visible by default, but could be visible if executing `my_app help --dev` or something like that.

**Comment by nolazybits** [comment]
I would like to add the following case:

You create a tool with many subcommands i.e 
`$ mycli project create`
`$ mycli module create`

Imagine you have many subcommand under project and module.
What would be nice is add a command `$ mycli project` and `$ mycli module` which will just output help text for those subcommand.
The other subcommand will have their help hidden.

It seems that to enable this I will only need to have the current requested feature as everything else is already there right?

**Comment by mattallty** [comment]
Done in #104
