### ISSUE TITLE
Add custom usage

### ISSUE THREAD

**Issue by tjbenton** [mattallty/Caporal.js#105]
It would be nice to add your own custom usage to make it more helpful for end users.

```js
program
  .usage('<command> [options] <...models>')
```

Here's the workaround I'm using to add custom usage.

```js
program._helper.__getUsage = program._helper._getUsage
program._helper._getUsage = function _getUsage (cmd) {
  const help = this.__getUsage(cmd).split('\n')
  help.splice(2, 1, `     ${chalk.italic(this._program.name() || this._program.bin())} <command> [options] [models...]`)
  return help.join('\n')
}
```

**Comment by fabiospampinato** [comment]
You can do that, albeit not super easily, check out [these](https://github.com/fabiospampinato/autogit/blob/master/src/cli.ts/#L83-L92) lines from one of my apps.
