### ISSUE TITLE
Option with no value?

### ISSUE THREAD

**Issue by jwbennet** [mattallty/Caporal.js#107]
Is it possible to use this to create an option which does not take a value?  For instance, I'd like to add a flag like `--do-stuff` which will be treated as a boolean value when it exists in the arguments for the program.  Here's an example of how I'd use it:

```javascript
program
  .command('myapp')
    .option('--do-stuff')
    .action(({}, { doStuff }, logger) => {
      if(doStuff) {
        logger.info('do stuff');
      } else {
        logger.info('stay put');
      }
    });
```

Then interacting with that flag from the command line would look like this:
```
$ myapp --do-stuff
do stuff
$ myapp
stay put
```

Is this supported already and I am missing something?  Thanks a bunch!

**Comment by mattallty** [comment]
Hi! You may want to the boolean validator, like this:

```js
program
  .command('myapp')
    .option('--do-stuff', 'Do something', program.BOOLEAN)
    .action(({}, { doStuff }, logger) => {
      if(doStuff) {
        logger.info('do stuff');
      } else {
        logger.info('stay put');
      }
    });
````

**Comment by jwbennet** [comment]
That does work, but its behavior is a bit odd if you also have an argument:

```javascript
program
  .command('myapp')
    .argument('[value]')
    .option('--do-stuff', 'Do something', program.BOOLEAN)
    .action(({}, { doStuff }, logger) => {
      if(doStuff) {
        logger.info('do stuff');
      } else {
        logger.info('stay put');
      }
    });
```

With the above the following works fine:

```
$ myapp value --do-stuff
do stuff
$ myapp --do-stuff=true value
do stuff
```

The odd behavior comes if you put the flag before the argument but do not add an explicit value for the flag:

```
$ myapp --do-stuff value
   Error: Invalid value 'value' for option --do-stuff.
```

Any thoughts?

**Comment by mattallty** [comment]
What about this ?

````
program
  .command('myapp')
    .argument('[value]')
    .option('--do-stuff [doit]', 'Do something', program.BOOLEAN)
    .action(({}, { doStuff }, logger) => {
      if(doStuff) {
        logger.info('do stuff');
      } else {
        logger.info('stay put');
      }
    });

```

in this example, adding `[doit]` means your option can take an optional value.

**Comment by jwbennet** [comment]
That appears to return the same as before since I think it is trying to validate that the `value` argument is a boolean value for the flag when it is not.

**Comment by mattallty** [comment]
yes you're right

**Comment by phra** [comment]
any ETA on this?

**Comment by mmmeff** [comment]
Bump

**Comment by phra** [comment]
@mattallty please push the latest release on npm. the latest one is 8 months old.
