### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by ivan-kleshnin** [mattallty/Caporal.js#108]
Tried to replace Commander with Caporal today. Not much luck unfortunately – some cases, like `action` API, are better in Caporal, some brought me new issues:

#### 1) Undefined commands throw weird errors

```
babel-node caporal.js sfjdsnfsfb

   Error: Wrong number of argument(s). Got 1, expected exactly 0.
```

No stack, no clues what went wrong... 😞 

#### 2) API mistakes result in the same error:

```
cli
  .command("buildPage [pattern]") // Commander style
  // .argument("[pattern]")
  .action((args, opts) => {
    console.log("args:", args)
    console.log("opts:", opts)
  })
```

```
babel-node caporal.js buildPage x

Error: Wrong number of argument(s). Got 2, expected exactly 0.
   Type caporal.js --help for help.
```

#### 3) No option to intercept undefined command

```
prog.on("*", () => {
  console.log("Unknown command!")
}) // Was possible in Commander. How to do that in Caporal?
```

😞

**Comment by mattallty** [comment]
Hi @ivan-kleshnin,

thanks for your feedback.

1) What was your code ?
2) Of course if you don't declare any possible argument...
3) Good idea!

**Comment by ivan-kleshnin** [comment]
For 1):

```js
import cli from "caporal"

cli
  .version("1.0.0")

cli
  .command("buildPage [pattern]")
  // .argument("[pattern]")
  .action((args, opts) => {
    console.log("args:", args)
    console.log("opts:", opts)
  })
```

My point is that CLI library should say something like "Unknown command. Use help..." in such cases.

2) Ok, maybe this one is overstretched. But still:

```
Error: Whatever
   Type caporal.js --help for help.
```

looks too close to basic JS error especially with that "Type caporal" shiften to the right.
So it makes you think what's going on – is that JS error or Caporal warning.

**Comment by mattallty** [comment]
Please excuse the (veryyy) late reply:

For 1), you `command()` call is wrong (commander style indeed).
If you correctly call command method with something like that:

```js
import cli from "caporal"

cli
  .version("1.0.0")

cli
  .command("buildPage")
  .argument("[pattern]")
  .action((args, opts) => {
    console.log("args:", args)
    console.log("opts:", opts)
  })
```

Then when typing `babel-node caporal.js sfjdsnfsfb`, caporal should be now displaying help, not the "Wrong number of argument(s)" error.

**Comment by ivan-kleshnin** [comment]
Thank you, Matt! Better late than never 😉

**Comment by baerrach** [comment]
Raising the dead.

What was the solution to 3) No option to intercept undefined command

The default behaviour is to display the help, but it should also indicate why the help was displayed with the "Unknown command: XXXX" type error.
