### ISSUE TITLE
Is it possible to specify global options

### ISSUE THREAD

**Issue by tonyxiao** [mattallty/Caporal.js#110]
that applies to all the subcommands?

**Comment by mattallty** [comment]
Hi, no it's not possible

**Comment by tonyxiao** [comment]
@mattallty do you find them not useful? I'm currently using env var as a workaround, which actually works reasonably well fwiw.

**Comment by fenixphp** [comment]
Faced with the fact that such an opportunity is very necessary. In modular application, many options are duplicated.

**Comment by oliversturm** [comment]
This is a real show-stopper. Being able to add global options is vital!
