### ISSUE TITLE
How to test programs created with Caporal?

### ISSUE THREAD

**Issue by frenzzy** [mattallty/Caporal.js#111]
Could you add some tests to pizza example?

https://github.com/mattallty/Caporal.js/blob/4950a755ea8da2ca7323d67cee72aead2f5951a4/examples/pizza/package.json#L7

Or add some info to readme file how to test cli tools (self executing files) like this one:

https://github.com/mattallty/Caporal.js/blob/4950a755ea8da2ca7323d67cee72aead2f5951a4/examples/pizza/pizza.js#L1-L4

**Comment by mattallty** [comment]
thanks for the suggestion, will do in future releases
