### ISSUE TITLE
Sub-commands

### ISSUE THREAD

**Issue by ThatTomPerson** [mattallty/Caporal.js#12]
You say you took inspiration from commander js, from what I see you don't support sub-commands, which personally think is one of the most important features of a CLI framework. do you have plans for including a sub-command structure?

eg `aws ec2 describe-instances`

commander does this with a child process

and yargs supports this as well with `require` calls
```
program.command(require('./command.js'))
```

**Comment by mAAdhaTTah** [comment]
I would consider migrating from commander for the bash completion but I'm using commander's git-style subcommands. Open to a PR for it?

**Comment by magicdawn** [comment]
like: git config get --global key
or we should use git-config/aws-ec2 as a program ?

**Comment by ThatTomPerson** [comment]
@mAAdhaTTah I personally prefer the yargs method of requiring the files

It means I can compile the cli down to a single file with rollup / webpack and make it easier for the guys at work to download and use

**Comment by mattallty** [comment]
Hi @ThatTomPerson 

About sub-commands, does this work for you ?

```js
const prog = require('caporal');

prog
  .version('1.0.0')
  .command('ec2 describe-instances', 'Describe instances')
  .action((args, opts, logger) => logger.info("Instances list..."))
  .command('ec2 describe-hosts', 'Describe hosts')
  .action((args, opts, logger) => logger.info("Hosts list..."))

prog.parse(process.argv);
```

If you want to split multiple sub-commands into several files, I think I can easily add a dedicated method for this.
Does the following API would be OK ?

```javascript
// filename: ec2
const prog = require('caporal');

prog
  .version('1.0.0')
  // autoload subcommands files :  'ec2-*'
  .loadSubCommands('/path/to/sub-commands/'); // optional path, default to `__dirname`

prog.parse(process.argv);
```

```javascript
// filename: ec2-describe-instances.js
const prog = require('caporal');

prog
 .command('ec2 describe-instances')
 .action((args, opts, logger) => logger.info("Instances list..."))
```

```javascript
// filename: ec2-describe-hosts.js
const prog = require('caporal');

prog
 .command('ec2 describe-hosts')
 .action((args, opts, logger) => logger.info("Hosts list..."))
```

**Comment by mAAdhaTTah** [comment]
I suspect `loadCommands` won't work for his "bundle with WebPack" usecase, as WebPack won't see `loadCommands` as a require call.

You also shouldn't need to re-add the prefix in the individual commands files, otherwise I would just include everything in one file, e.g:

```
// filename: ec2-describe-instances.js
const prog = require('caporal');

prog
  // es2 is implied
 .command('describe-instances')
 .action((args, opts, logger) => logger.info("Instances list..."))
```

**Comment by mattallty** [comment]
In my mind, loadCommands() would require() files. Don't know exactly how webpack handle this.
You're right about the ec2 prefix, as in my example it's the cli name. 
Let me push a feature branch we can talk about.

**Comment by mAAdhaTTah** [comment]
As long as the values passed to `require` are dynamic, WebPack won't be able to interpret it.

Sounds like a plan.

**Comment by ThatTomPerson** [comment]
your `loadCommands` example won't work for module bundlers (same problem with commander)

you could have an api like
```
// filename: index.js
const prog = require('caporal');

prog
  .version('1.0.0')
  .command('ec2')
  .action(require('./ec2.js'))

prog.parse(process.argv);
```

```
// filename: ec2.js
const prog = require('caporal');

export default prog
  .version('1.0.0')
  .command('describe-instance')
  .action(function () {})
```

or better yet if the subcommand `ec2.js` could export its name 
```
export const name = 'ec2'
```
so that the parent `index.js` could just refrance the file

```
// filename: index.js
const prog = require('caporal');

prog
  .version('1.0.0')
  .command(require('./ec2.js'))

prog.parse(process.argv);
```

**Comment by mattallty** [comment]
If the only way to make it webpack compatible why not using `require()` directly like this:

```javascript
// filename: ec2
const prog = require('caporal');
prog
  .version('1.0.0')

require('./ec2-describe-instances.js');
require('./ec2-describe-hosts.js');

prog.parse(process.argv);
```

```javascript
// filename: ec2-describe-instances.js
const prog = require('caporal');
prog
  .command('describe-instances')
  .action('...')
```

```javascript
// filename: ec2-describe-hosts.js
const prog = require('caporal');
prog
  .command('describe-hosts')
  .action('...')
```


Usage:

```bash
ec2 describe-instances
// or
ec2 describe-hosts
```

**Comment by mattallty** [comment]
Closing as simply calling require() would do the job, please reopen if needed.

**Comment by trusktr** [comment]
@mattallty I think you closed this with the wrong assumption. Your example, with `require` only allows one level of nesting. They aren't "subcommands".

In your example, the usage is

```
ec2 describe-instances
// or
ec2 describe-hosts
```

but what this issue describes to achieve is more like this:

```
aws ec2 describe-instances
// or
aws ec2 describe-hosts
```

or

```
gitcli remote prune origin
// or
gitcli remote add origin $URL
```

Other tools alternative tools, like yargs or vorpal, allow nesting to achieve this. 

Examples with yargs:

- With folder hierarchy: https://github.com/yargs/yargs/blob/master/docs/advanced.md#example-command-hierarchy-using-commanddir
- With nested functions: https://github.com/yargs/yargs/issues/225#issuecomment-128532719

The really neat thing about the Yargs' nested folder feature is that yargs only `require()`s the files needed for the command being executed, which makes loads times much faster (compared to requiring all files at once).

Another CLI tool inspired by Yargs is http://sywac.io, which also has similar command nesting and features (as well as other options like built-in type checking of inputs).

**Comment by nexdrew** [comment]
> The really neat thing about the Yargs' nested folder feature (haven't checked Sywac, @nexdrew can you chime in?) is that yargs only `require()`s the files needed for the command(s) being executed, which makes load times much faster (compared to requiring all files at once).

Yes, sywac works the same way (I actually wrote [both](https://github.com/yargs/yargs/pull/494) [implementations](https://github.com/sywac/sywac/pull/5)). Subcommands follow a path down a tree/DAG, and all commands are loaded at each level of the path so command-matching works at any given level, but subcommands for any other levels not on the given path are not loaded. Hopefully that makes sense.
