### ISSUE TITLE
security issue lodash 3.10.1

### ISSUE THREAD

**Issue by qballer** [mattallty/Caporal.js#120]
Lodash 3.10.1 has a security issue. Any chance to update dependencies?

**Comment by qballer** [comment]
the issue originates from cli-table2 which removed lodash 3.10.1 and didn't publish a version to npm.

**Comment by BrandonOCasey** [comment]
Should be fixed by https://github.com/mattallty/Caporal.js/pull/115

**Comment by qballer** [comment]
@BrandonOCasey  one the tests pass can you release a version?

**Comment by BrandonOCasey** [comment]
sorry for the confusion, I am not a maintainer here

**Comment by mattallty** [comment]
Fixed in v1.0.0
