### ISSUE TITLE
Aliases for options

### ISSUE THREAD

**Issue by bluzi** [mattallty/Caporal.js#121]
Would love to be able to create aliases for options, something like: `--name/-n`, `--objectId/-o`, etc.

**Comment by kinok** [comment]
Hi @bluzi,

You can use aliases with short or long name in options as per in [example pizza file](https://github.com/mattallty/Caporal.js/blob/master/examples/pizza/pizza.js#L27) like so:
`.option('-n, --number <num>', 'Number of pizza', prog.INT, 1)`

**Comment by bluzi** [comment]
Oops, sorry, couldn't find in the docs. :)
