### ISSUE TITLE
Custom flag support

### ISSUE THREAD

**Issue by GopherJ** [mattallty/Caporal.js#126]
Hello, I noticed that currently caporal doesn't have flag support. Do you have a plan to add that ?

```js
program
   .flag('-q, --quiet', 'disable verbose output');
   .action((args, options, flags, logger) => {
    if (flags.quiet) {//}
});
```

or compatible changes

```js
program
   .option('-q, --quiet', 'disable verbose output');
   .action((args, options, logger) => {
    // options.quiet  === true
    if (options.quiet) {//}
});
```

**Comment by mattallty** [comment]
Hello, option() does the job, don’t you think ?
Also caporal supports a few global flags (named global options), like
—verbose

Le mar. 27 nov. 2018 à 18:05, Cheng JIANG <notifications@github.com> a
écrit :
