### ISSUE TITLE
How can I  remove default global options?

### ISSUE THREAD

**Issue by StinsonZhao** [mattallty/Caporal.js#127]
I don't want the global options like `--no-color`, but I can't find any api to disable it or hide it. I know a tedious idea, that's to custom the help display. But that means I will custom all items of my cmd-line app.

Any idea?

**Comment by bookmoons** [comment]
Also very interested in this. I have a very simple app that would be best with a minimal interface. The standard help is so nice but I'd rather not show my users options that have no effect.

**Comment by mattallty** [comment]
I could find a way to disable color-related global options as well as verbosity, but will have to keep --help and --version

**Comment by bookmoons** [comment]
Thanks for considering @mattallty. That would be wonderful. Help and version I'd both like to keep, so it would work well.

**Comment by vasanthdeveloper** [comment]
Any progress on this? I am also interested to remove `--no-color` but also how to add custom global option? There doesn't seem to be a way to do it. :disappointed:

**Comment by mattallty** [comment]
Hey there - I've released `beta` of the next Caporal (`v2`). The v2 is a full rewrite of Caporal in Typescript. 

**Caporal v2 now allows you to remove/add global options.**

Be warned that, while most of the usage remain the same, the v2 is **not** backward compatible with v1.

You can test it with `npm install @caporal/core@beta`

- Docs are available here: https://beta.caporal.io 
- You may want to be specifically interested in the  **migration guide** located here: https://beta.caporal.io/guide/migration.html

Feel free to open issues regarding v2. I would also be happy if you have any feedbacks / suggestions.
