### ISSUE TITLE
Looking for a maintainer?

### ISSUE THREAD

**Issue by fabiospampinato** [mattallty/Caporal.js#129]
Hey @mattallty, I see this package is no longer actively maintained. 

Since I've made more than a handful CLI apps using it I'd say I'm pretty invested in it, so I was wondering if you'd be interested in having me maintaining it.

I'd like to rewrite it from scratch in TypeScript, at some point in the near-ish future, with performance as a goal, while still maintaining as much API compatibility as possible. Currently CLI apps written on top of Caporal start-up slowly, and Caporal itself is pretty bloated, requiring ~10MB of dependencies (mostly coming from `tabtab`). The readme should be reorganized as well I think.

I'll understand if you don't want a third-party basically taking over the project, in that case I'd just rebrand mine Colonel.js or something and move on. 

Let me know 👍

**Comment by mattallty** [comment]
Hi @fabiospampinato, thanks for your interest, could you please tell me on what email address I can write you ? Thanks !

**Comment by fabiospampinato** [comment]
Sure, you can find me at spampinabio@gmail.com

**Comment by mattallty** [comment]
closing here, continuing discussion by email
