### ISSUE TITLE
Enter negative number as Argument

### ISSUE THREAD

**Issue by tungptseven** [mattallty/Caporal.js#13]
I'm trying to get data from user by console to solve quadratic. It run successfully even when I entered 3 float numbers.
But when I enter Negative number it does not work, eg: 
`node caporalDemo.js solve 7 8 -2`
it say 
`Error: Wrong number of argument(s) for command solve. Got 2, expected exactly 3.`
My `caporalDemo.js --help` : 
caporalDemo.js 1.0.0 
     
   USAGE

     caporalDemo.js solve <a> <b> <c>

   ARGUMENTS

     <a>      Value of a      required      
     <b>      Value of b      required      
     <c>      Value of c      required       `

So How can I input Negative arguments ?

**Comment by Milewski** [comment]
I think you could try to wrap your number with '-2', I had a similar issue using a lib like this before with the same issue... And adding in quotes solved..

**Comment by tungptseven** [comment]
@Milewski Thanks for your suggestion but it still not work

**Comment by mattallty** [comment]
Thanks for your feedback @tungptseven, working on it, will push a PR very soon.

**Comment by mattallty** [comment]
@tungptseven Could you please test your case against PR #16 ? Your example should now pass.

**Comment by tungptseven** [comment]
Thank you very much for your help!
