### ISSUE TITLE
Error setting up completion in bash

### ISSUE THREAD

**Issue by gcox** [mattallty/Caporal.js#136]
I get the following error when I try to setup auto completion in bash (macOS 10.14):

```
$ source <([app name] completion bash)
$ Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket.dummyDestroy [as _destroy] (internal/process/stdio.js:11:34)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:790:10)
```

This happens with my own cli and with the example cli. 

For recreating with the example app;
1. `cd` to `examples/pizza`
2. run `npm install`
3. run `npm link`
4. run `fly` to confirm the command is installed
5. run `source <(fly completion bash)`. This is when the error is thrown

**Comment by mattallty** [comment]
Strange, cannot reproduce in Mac OS 10.14.4
What if you just run `./[app name] complexion bash` ?

**Comment by gcox** [comment]
I'm running 10.4.4 as well.

Here's the output:
``` bash
~/dev/theirs/caporal/examples (master)$ fly completion bash
###-begin-fly-completion-###
if type complete &>/dev/null; then
  _fly_completion () {
    local words cword
    if type _get_comp_words_by_ref &>/dev/null; then
      _get_comp_words_by_ref -n = -n @ -w words -i cword
    else
      cword="$COMP_CWORD"
      words=("${COMP_WORDS[@]}")
    fi

    local si="$IFS"
    IFS=$'\n' COMPREPLY=($(COMP_CWORD="$cword" \
                           COMP_LINE="$COMP_LINE" \
                           COMP_POINT="$COMP_POINT" \
                           fly completion -- "${words[@]}" \
                           2>/dev/null)) || return $?
    IFS="$si"
  }
  complete -o default -F _fly_completion fly
fi
###-end-fly-completion-###

~/dev/theirs/caporal/examples (master)$ 
```

**Notes**
1. If I paste that into my `.bashrc` file and do not include `source <(fly completion bash)`, there is no error and completion works.
2. If I paste that into another file, and source that file, there is no error and completion works. 
3. If I use `eval "$(fly completion bash)"` in my `.bashrc`, there is no error and completion works.
4. I see there was a related [PR in tabtab](https://github.com/mklabs/tabtab/pull/4/commits/4fca6aaf04b30b04e3c66e46dd87b90c43b49bbc) a long time ago, but it looks like that logic was removed sometime between then and v2.x.

Not sure if I'm losing anything by using `eval "$(fly completion bash)"`, but that seems like the most convenient work around for me.

**Comment by gcox** [comment]
Actually, completion only seems to work for commands, not arguments or options.

**Comment by gcox** [comment]
More info...

*suggestions* work for arguments/options, but completion does not. Example:
```
$ fly order [tabtab]
--add-ingredients  --number           -e                 hawaiian           
--discount         --pay-by           fredo              margherita

$ fly order haw[tabtab] <---nothing happens 
```

**Comment by mattallty** [comment]
what version are testing against ? `master` branch ? Or any previous version ?

**Comment by gcox** [comment]
`master` branch

**Comment by mattallty** [comment]
Maybe it’s the promise validation that broke this ? Could you try against
the last release from npm ?

**Comment by gcox** [comment]
Just did and I get the same behavior

**Comment by mattallty** [comment]
Ok, reading the code, I don't think that ever worked.

**Comment by mattallty** [comment]
Working on a fix

**Comment by mattallty** [comment]
Could you please try against this branch: https://github.com/mattallty/Caporal.js/commits/fix-issue-136
Warning: I've renamed the `pizza` bin entry of the example's package.json from `fly` to `pizza`

It should fix argument completion (when a partial arg is written) . Its does *not* however fix the original EPIPE problem.

**Comment by mattallty** [comment]
Arg, no, forget what I said, I still have errors. Will work on it.

**Comment by gcox** [comment]
It does seem to be much improved though...seems like completion stops working once you get to a certain depth. At least with the pizza example, it seems to work correctly until you get to the <account> argument (meaning it won't complete partially entered accounts)

**Comment by mattallty** [comment]
I've pushed more commits on [https://github.com/mattallty/Caporal.js/commits/fix-issue-136](fix-issue-136), seems working like expected on my setup with ZSH.

**Comment by mattallty** [comment]
no problem, this is great news, thanks for your feedback 👍
