### ISSUE TITLE
Support promise based validation

### ISSUE THREAD

**Issue by gcox** [mattallty/Caporal.js#137]
Like with the completion feature, it would be nice to support promise based validation of arguments/options.

### Example usage

***Update 5/1/19*** Usage now matches up with how the function validator is supposed to work, had misunderstood this.
``` typescript
function fetchAllNames(): Promise<string[]> {
  ...
}

command('commandname')
  .argument(
    '<name>', 
    'name from a dynamic list of possible names', 
    arg => fetchAllNames().then(names => {
      if (names.includes(arg)) {
        return arg;
      }
      throw new Error(`Valid names are [${names.join(', ')]`);
    })
  )
```

**Comment by mattallty** [comment]
Excellent suggestion. Will work on it!

**Comment by gcox** [comment]
@mattallty I've actually made good progress on this so I'm going to start a draft PR
