### ISSUE TITLE
Usage information not being autogenerated on a command level

### ISSUE THREAD

**Issue by juvoni** [mattallty/Caporal.js#14]
The help command/opt seems to only be outputting high-level program usage information, i.e list of commands and required input. 

> Caporal automatically generates help/usage instructions for you. Help can be displayed using -h or --help options, or with the default help command.

Makes sense for the framework to also support usage information on the command level.

`pizza order -h`

In this example, the help usage should show any required arguments for this command as well as the options and their descriptions.

**Recording of Issue**

[![asciicast](https://asciinema.org/a/e59gpz2b0d99dalmhi89p1x1c.png)](https://asciinema.org/a/e59gpz2b0d99dalmhi89p1x1c)

**Comment by mattallty** [comment]
Thanks for the feedback @juvoni, perfectly right, Im' going to fix this.
