### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by vlaraort** [mattallty/Caporal.js#145]
**Describe the bug**
The artifact published in the NPM repository is outdated and don't reflect the last changes in the source code

**Expected behavior**
The NPM artifact should be aligned with the code in master branch

**Additional context**
Please, make a publish with the latest changes :)

**Comment by digodiego8** [comment]
cmon' guys!!!!

**Comment by mattallty** [comment]
[1.2.0](https://www.npmjs.com/package/caporal/v/1.2.0) has been released

**Comment by vlaraort** [comment]
Perfect, thank you 😊
