### ISSUE TITLE
Function validators only work if they return promises

### ISSUE THREAD

**Issue by bwinterton** [mattallty/Caporal.js#149]
**Describe the bug**
Due to the change in [6c67c95](https://github.com/mattallty/Caporal.js/commit/6c67c95) validator functions that return a value, rather than a promise, cause the option to be set to undefined as the value is not returned by the `_validateWithFunction()` function.

**To Reproduce**
1. Create an option with a function validator. For example the simple example below:
```js
function list(value: any): string[] {
    if (typeof value !== 'string') {
        throw new Error(`Invalid value: '${value}'`);
    }
    return value.split(',');
}
```
2. Run the command with the option set, the value comes out as undefined.

**Expected behavior**
My understanding is that the previous change should not have required validator functions to use promises as the examples in the README still return values directly. As such, validator functions that return values rather than promises should also function as they did previously. 

**Environment informations (please complete the following information):**
 - OS: Mac
 - OS version: Mojave
 - Shell: Bash
 - Caporal version: 1.2.0

**Comment by bwinterton** [comment]
As a note, I am currently working on a pull request to fix this issue. In writing tests to validate the fix, it seems like function validators that return promises are also not working for options.

**Comment by mattallty** [comment]
Thanks a lot! Seems like we’re missing some more tests because all of them
were passing.

**Comment by mattbishop** [comment]
👍

**Comment by toovy** [comment]
@mattallty also ran into this issue, it seems to be merged but I guess it is not released yet?

**Comment by khaosdoctor** [comment]
I just ran into this issue too...

**Comment by ValYouW** [comment]
Please release a new version with this fix...
