### ISSUE TITLE
postinstall script crashes consumer application

### ISSUE THREAD

**Issue by bennyn** [mattallty/Caporal.js#151]
**Describe the bug**
I published an application on npm which uses caporal as dependency. When installing my application as a global node package, I am getting the following error:

> C:\Users\bennyn>npm i -g swaxios
> C:\Users\bennyn\AppData\Roaming\npm\swaxios -> > C:\Users\bennyn\AppData\Roaming\npm\node_modules\swaxios\dist\cli.js
> core-js@2.6.8 postinstall C:\Users\bennyn\AppData\Roaming\npm\node_modules\swaxios\node_modules\core-js
> node -e "try { require('./scripts/postinstall'); } catch (e) { /* empty */ }"
>Thank you for using core-js ( https://github.com/zloirock/core-js )!
>Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock
> spawn-sync@1.0.15 postinstall C:\Users\bennyn\AppData\Roaming\npm\node_modules\swaxios\node_modules\spawn-sync
> node postinstall
> caporal@1.2.0 postinstall C:\Users\bennyn\AppData\Roaming\npm\node_modules\swaxios\node_modules\caporal
> (test -f ./node_modules/husky/bin/install.js && node ./node_modules/husky/bin/install.js) || exit 0

**To Reproduce**

```bash
npm i -g swaxios@0.0.1
```

**Expected behavior**
No error message from Caporal's "postinstall" npm script.

**Environment informations (please complete the following information):**
 - OS: Windows
 - OS version: 10
 - Shell: cmd
 - Caporal version: 1.2.0

**Screenshot**

![image](https://user-images.githubusercontent.com/469989/58337453-1c5a4800-7e46-11e9-853c-25d0f99b1db6.png)

**Comment by rajeshduggal** [comment]
"test -f " fails on windows.
