### ISSUE TITLE
lodash security vulnerabiity

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [mattallty/Caporal.js#153]
You have version `4.17.11` of `lodash` explicitly specified as a dependency.  A security vulnerability currently exists for `<4.17.13`.  https://github.com/lodash/lodash/issues/4348

I'm happy to submit a PR referencing the most recent `lodash` version to resolve this; however, I wanted to see if you would prefer that or to adopt the `^` as you have other dependencies?

**Comment by mattallty** [comment]
Thank you for the report, fixed in #154
