### ISSUE TITLE
Basic operation just doesn't work

### ISSUE THREAD

**Issue by russellrobinson** [mattallty/Caporal.js#155]
**Describe the bug**
If you have a mandatory argument, Caporal completely fails to work if you specify an option.

**To Reproduce**
1. Run the program with "FRED" as the argument. The program works and displays the args and options.
2. Run the program with "--quiet FRED" (or any other option), the program says "Error: Wrong number of argument(s). Got 0, expected exactly 1."

Of course, for a real program where I add my own options, Caporal has the same problem.
```js
program
        .version('0.0.1')
        .description('Coolpacket')
        .argument('<arg>', 'A mandatory argument')
        .action(function (args: object, options: object, logger: Logger) {
            console.log(options);
            console.log(args);
        });
program.parse(process.argv);
```

**Expected behavior**
If you provide options on the command line, the mandatory argument should be accepted.

**Environment informations (please complete the following information):**
 - OS: Linux
 - OS version: Ubuntu 18.04.2
 - Shell: bash
 - Caporal version: 1.2.0

**Additional context**
There are additional problems as well:

- .complete doesn't work with .options
- the "USAGE" output does show any [options] component even if I provide my own options

**Comment by mattallty** [comment]
Actually the arg parser used in Caporal does not have the whole context of the program, meaning that it does not know if you mean `--quiet=true FRED` or `--quiet FRED` (as if FRED was the value for the option --quiet.

The current workaround is to pass the arg before, like:

`./my-prog FRED --quiet`
