### ISSUE TITLE
Another basic operational bug

### ISSUE THREAD

**Issue by russellrobinson** [mattallty/Caporal.js#156]
**Describe the bug**
If you supply multiple values for an option, only one of them works.

**To Reproduce**

1. Create an option that can have 2 values (e.g. short and long)
2. Run the program with one option.
3. Display its value.
4. Run the program with the other option.
5. Display its value.

Creating long and short options:
```js
program.option('--temp,--temperature', ...)
```

**Expected behavior**
Either option when used should provide a value in the program.

**Environment informations (please complete the following information):**
 - OS: Linux
 - OS version: Ubuntu 18.04.2
 - Shell: bash
 - Caporal version: 1.2.0

**Additional context**

**Comment by mattallty** [comment]
Short option should be prefixed by only one dash, like `-s`, and long options by double dashes, eg `--long-opt`.
