### ISSUE TITLE
Option - cannot combine short and long flag when using repeatable

### ISSUE THREAD

**Issue by edosrecki** [mattallty/Caporal.js#163]
**Describe the bug**
It is not possible to combine short and long versions of option flag when using repeatable option.

**To Reproduce**
```js
program
  .command('command')
  .option('-k, --key <val>', '', program.REPEATABLE)
  .action((args, opts) => {
    console.log({ args, opts })
  })
```

Running `command --key 1 -k 2 --key 3` logs:
```
{ args: {}, opts: { key: '2' } }
```

**Expected behavior**
Expected it to log:
```
{ args: {}, opts: { key: ['1', '2', '3'] } }
```

**Environment informations (please complete the following information):**
 - OS: MacOS
 - OS version: 10.13.6
 - Shell: fish
 - Caporal version: 1.3.0

**Comment by mattallty** [comment]
Hey there - I've released `beta` of the next Caporal (`v2`). The v2 is a full rewrite of Caporal in Typescript. This issue should be addressed in v2.

Be warned that, while most of the usage remain the same, the v2 is **not** backward compatible with v1.

You can test it with `npm install @caporal/core@beta`

- Docs are available here: https://beta.caporal.io 
- You may want to be specifically interested in the  **migration guide** located here: https://beta.caporal.io/guide/migration.html

Feel free to open issues regarding v2. I would also be happy if you have any feedbacks / suggestions.
