### ISSUE TITLE
--no-color does not work since chalk -> colorette swap

### ISSUE THREAD

**Issue by koczkatamas** [mattallty/Caporal.js#165]
**Describe the bug**
The `--no-color` option was supported by `chalk` which was replaced in PR https://github.com/mattallty/Caporal.js/pull/117 in Oct 2018 to `colorette` which does not support this argument.

**To Reproduce**
Run any app with `./app --help --no-color` and you will see that there are still colors.

**Expected behavior**
No color should be displayed.

`colorette` supports `NO_COLOR` environment variable, so you can test the expected behaviour by running `NO_COLOR=1 ./app`.

**Environment informations (please complete the following information):**
 - OS: [e.g. Linux, Mac]: Mac
 - OS version: 10.15.2
 - Shell [e.g. bash, zsh, fish]: bash
 - Caporal version [e.g. 1.0.1]: 1.1.0

**Additional context**
May worth create test for this argument as it is a global argument available in all apps, but it still does not work for more than 1 year.

**Comment by vasanthdeveloper** [comment]
I wonder why nobody took this seriously. 🤔 
Even if I submit a PR, it will take some time to get accepted...

**Comment by mattallty** [comment]
Hey there - I've released `beta` of the next Caporal (`v2`). The v2 is a full rewrite of Caporal in Typescript. This issue should be addressed in v2 as it now uses `chalk`.

Be warned that, while most of the usage remain the same, the v2 is **not** backward compatible with v1.

You can test it with `npm install @caporal/core@beta`

- Docs are available here: https://beta.caporal.io 
- You may want to be specifically interested in the  **migration guide** located here: https://beta.caporal.io/guide/migration.html

Feel free to open issues regarding v2. I would also be happy if you have any feedbacks / suggestions.
