### ISSUE TITLE
Setting verbose mode doesn't set the logger level do 'debug'

### ISSUE THREAD

**Issue by karlitos** [mattallty/Caporal.js#172]
**Describe the bug**
I searched for a way to detect, whether the `-v/--verbose` flag was set. My expectation was to look at the __level__ attribute of the logger parameter in the __action__ call.

**To Reproduce**

```js
program.command('test', 'Just a test')
	.action((args, options, logger) => {
                 // is always 'info'
		console.log(logger.level)
	});
program.parse(process.argv);
```

**Expected behavior**
My expectation was, that running the cli with the `-v/--verbose` flag would set the level to _debug_

**Environment informations (please complete the following information):**
 - OS: Mac
 - Shell: bash
 - Caporal version: 1.3.0

**Additional context**
If my suggestion was wrong, could you please tell me how to detect the `-v/--verbose` flag  ?

**Comment by jhorbulyk** [comment]
It looks like the logging level is set on each of the loggers transports but not on the logger itself: https://github.com/mattallty/Caporal.js/blob/db1981314e2f01b61cd596bdf0baf80a1787aec4/lib/program.js#L185-L188

**Comment by karlitos** [comment]
Many thanks for your reply. But I don't fully understand what does it mean regarding my intention to detect the global verbose settings. I realized I can get the __debug/info__ flog from `logger.transports.caporal.level`, but is it a good/recommended way of doing it ?

**Comment by karlitos** [comment]
Hi, may I ask if there will be any further development regarding the setting the log level on the logger or whether I shall use `logger.transports.caporal.level` ?

**Comment by mattallty** [comment]
Hey there - I've released `beta` of the next Caporal (`v2`). The v2 is a full rewrite of Caporal in Typescript. This issue should be addressed in v2.

Be warned that, while most of the usage remain the same, the v2 is **not** backward compatible with v1.

You can test it with `npm install @caporal/core@beta`

- Docs are available here: https://beta.caporal.io 
- You may want to be specifically interested in the  **migration guide** located here: https://beta.caporal.io/guide/migration.html

Feel free to open issues regarding v2. I would also be happy if you have any feedbacks / suggestions.

**Comment by karlitos** [comment]
I can confirm, that v2 version solved my problem, I updated my project to use caporal v2 and so far - so good

**Comment by mattallty** [comment]
Great news - what is the v2 version you're using ?

**Comment by mattallty** [comment]
I'm planning to release a stable version for v2 - But I don't have a lot of feedbacks so far

**Comment by karlitos** [comment]
> Great news - what is the v2 version you're using ?

"@caporal/core": "^2.0.0-beta.2",

**Comment by mattallty** [comment]
I've released a final version + some fixes over the week-end, you should be
able to install @caporal/core@2.0.2
