### ISSUE TITLE
 Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency

### ISSUE THREAD

**Issue by harikrishnan-a-k** [mattallty/Caporal.js#180]
writing
const program=require('caporal') gives warning
Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency

**Comment by mattallty** [comment]
What version do you use ?

**Comment by mattallty** [comment]
Googling it, it seems like several repo have these errors with node.js 14 - on which version of Node and of Caporal do you use ?

**Comment by harikrishnan-a-k** [comment]
i was using node 14. version.. when changed it to node 12. LTS problem was solved

**Comment by juanantoniofj** [comment]
i am having the same issue using node 14, other previous versions works fine. It is related to some circular dependency, as a workaround you can invoke node with the "--no-warnings" option.
