### ISSUE TITLE
custom error and dispose handler

### ISSUE THREAD

**Issue by tugrul** [mattallty/Caporal.js#185]
**Is your feature request related to a problem? Please describe.**
I use caporal with awilix and awilix keeps db pools. I always call `container.dispose()` awilix function to close process in every action.

**Describe the solution you'd like**
We can give action wide and global wide `dispose` and `error` handler callbacks to caporal

**Describe alternatives you've considered**
Maybe caporal can have event dispatcher instead of to give callback to caporal

**Additional context**
I currently use following wrapper to avoid code repeat.

```javascript
function actionWrapper(action) {
    return async (args, options, logger) => {
        try {
            return await action(args, options, logger);
        } catch(err) {
            logger.error(err);
        } finally {
            container.dispose();
        }
    };
}
```

**Would you be able to work on it and provide a pull request ?**

I'm not familiar codebase of caporal maybe I can change my decision to yes later.
- [ ] Yes
- [X] No

**Comment by mattallty** [comment]
Interesting use case!


Turns out, the v2 of Caporal is out. Take a look at https://caporal.io

The program emit a "run" event after having run an action, so this should
fit you needs.

Let me know if this helps

**Comment by tugrul** [comment]
Thank you so much.

I switched to v2 and error handling looks well. I did not create special error handler.

Also `run` event listener is helped me

```javascript
program.on('run', () => {
    container.dispose();
});
```
