### ISSUE TITLE
Running an application importing caporal with no CLI arguments throws an error

### ISSUE THREAD

**Issue by edouardmercier** [mattallty/Caporal.js#199]
**Describe the bug**
An application integrates the caporal module and imports the caporal `program. When executing this application with no CLI parameters causes an error to be triggered while importing the caporal module.

**To Reproduce**
Run an application with no CLI parameters, the application should thrown an unhandled error.

**Expected behavior**
No error should be triggered.

**Actual behavior**
The hosting application should not experiment the following unhandled error:
```
Uncaught Exception:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.basename (path.js:1156:5)
```
This error is thrown at the level of the caporal import statement, i.e. `const {program} = require("@caporal/core");`, which means that the hosting application cannot reach the `program.run()` method invocation.

**Environment informations (please complete the following information):**

- OS: macOS
- OS 10.14.6:
- Shell: run within an Electron application
- Caporal version: 2.0.2

The issue seems to be located on line 97 of file `src/program/index.ts`, because of the `this._bin = path.basename(process.argv[1])`, which assumes that the command line contains at least one parameter.

**Comment by haykam821** [comment]
I don't think this is an issue with Caporal. I was able to trace this error to `fs-extra` by adding the following snippet:

```js
program.addListener("error", error => {
	console.log(error);
});
```

Once I removed the code that called `fs-extra`, this error stopped occurring.

**Comment by edouardmercier** [comment]
Sorry, @haykam821, you do not seem to address the reported issue, I do not understand what `fs-extra` has to do with this…

**Comment by edouardmercier** [comment]
@haykam821, @mattallty, unfortunately, the code does not support a use-case when the `process.argv` array variable only contains one element, which is the case in Electron applications. I have to lazy-load Caporal via a `const Caporal = await import("@caporal/core");` import statement as a work-around, and to add a dummy value to the `process.argv` just before that import.

If you decide to tackle this issue, that would be great. If you'd like me to submit a PR, please let me know.
