### ISSUE TITLE
The --quiet flag displays usage info

### ISSUE THREAD

**Issue by kingaiakab** [mattallty/Caporal.js#20]
When using the `--quiet` flag like this: `my_program --quiet test` I get usage info for the `test` command.

**Comment by mattallty** [comment]
Hi @kingaiakab, thanks for your feedback. 
Could you please tell me the Caporal version used ? And test you case against `master`?

**Comment by kingaiakab** [comment]
Hi @mattallty. I used version `0.3.0`

**Comment by mattallty** [comment]
What about `master` ? Did you try ?

**Comment by kingaiakab** [comment]
Yes, I tried with `master` too. It's the same result.

**Comment by mattallty** [comment]
Problem is that by passing options before arguments, caporal don't know if the argument is argument-value. Solution *for now* is to pass options at the end of the command line. Will document it.
