### ISSUE TITLE
Dependabot cannot update lodash to a non-vulnerable version

### ISSUE THREAD

**Issue by wirwolf** [mattallty/Caporal.js#239]
Hello.

Versions of lodash prior to 4.17.19 are vulnerable to Prototype Pollution. The function zipObjectDeep allows a malicious user to modify the prototype of Object if the property identifiers are user-supplied. Being affected by this issue requires zipping objects based on user-provided property arrays.

This vulnerability causes the addition or modification of an existing property that will exist on all objects and may lead to Denial of Service or Code Execution under specific circumstances.

In my project I use Caporal.js and I can not fix this issue and update loadash 

https://security.snyk.io/vuln/SNYK-JS-LODASH-73638

**Comment by mattallty** [comment]
3.0 has been released with updated deps: https://www.npmjs.com/package/@caporal/core
