### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by gilles-crealp** [mattallty/Caporal.js#243]
No answers from @mattallty since 2020...

**Comment by ryanrubleycoates** [comment]
Watching with interest, as we use this in a few projects and the warnings are becoming annoying. Would love to move over to a fork if somebody is going to pick it up

**Comment by cah4a** [comment]
Caporal.js is now the best solution I've seen. Would love to use a maintained fork.

**Comment by donmccurdy** [comment]
I'm using Caporal in my own project ([github.com/donmccurdy/glTF-Transform/](https://github.com/donmccurdy/glTF-Transform/)) and have gotten complaints from downstream users about the `npm audit` warnings from old dependencies. I have a pretty dim view of `npm audit` in general, but it would still be nice to keep these dependencies up to date, even if new feature development isn't planned.

After replacing GitHub's dependabot with Renovate (https://github.com/renovatebot/renovate) (free for open source) I've found that quite helpful. It can batch dependency updates into a single PR on a fixed schedule (weekly, monthly, ...) and merge the PR automatically if tests pass. I'd be willing to help set up something like that here if maintainers are interested.

**Comment by ryanrubleycoates** [comment]
We gave up and migrated everything to Commander with minimal pain today, and realized that it shaved about 3MB from our compressed .deb distributions as a bonus. I guess there are a LOT of deps in Caporal for things we didn't even use.

**Comment by donmccurdy** [comment]
I've gone ahead with forking the project, updating dependencies, and publishing a new build on npm as `@donmccurdy/caporal`. Feel free to use my fork if you'd like:

https://github.com/donmccurdy/Caporal.js

Unless the situation changes on the upstream project, I'll plan to strip down the build system to something I'm more comfortable maintaining, add Renovate for automatic dependency updates, and leave things alone beyond that. I don't have any personal plans to add features or change the API — Caporal has worked really well for me, and migrating to other CLI generators didn't make sense in my project. If others are interested in getting involved, feel free to comment over there.

**Comment by mattallty** [comment]
Hey - mostly dead as you can see :(

I'm now able re-work on it since I'm now free of work.

My plans are:
- clean the repo of vulnerabilities
- work on a v3, but be aware that it will be full of breaking changes since I've a totally different interface in mind.

The best advice I can give you for now is to use the fork of @donmccurdy: https://github.com/donmccurdy/Caporal.js

**Comment by mattallty** [comment]
@gilles-crealp @cah4a @donmccurdy 

I've spent the night re-looking at it. Not really sure it needs a V3 now.
I've a PR here that fixes _a lot_ but I'd be happy if some folks could test on some real use cases: 

https://github.com/mattallty/Caporal.js/pull/253

**Comment by mattallty** [comment]
@gilles-crealp @cah4a @donmccurdy

You should be able to test it using `npm install @caporal/core@next`
i've been able to successfully test it on my side

**Comment by mattallty** [comment]
[3.0 has been released](https://www.npmjs.com/package/@caporal/core) (major update because it requires Node 16+)
Closing this issue
