### ISSUE TITLE
Logger should attach the new line character at the end of prettified message

### ISSUE THREAD

**Issue by yuhwan** [mattallty/Caporal.js#25]
I just logged some messages including strings and objects with following code.
```javascript
.action(function(args, options, logger) {
  logger.warn('begin');
  logger.warn({ version: 'v1' });
  logger.warn({ version: 'v2' });
  logger.warn('end');
});
```
The logger does not print out each message in a proper way (i.e., each message in a line). The output is like below.
```
begin

version: v1
version: v2end
``` 

I suspect that the new line character should be attached at the end of prettified message in [this code](https://github.com/mattallty/Caporal.js/blob/master/lib/logger.js#L16). I think it should be like this.
```javascript
msg += prettyjson.render(meta) + "\n";
```

**Comment by mattallty** [comment]
Thank you for the bug report @yuhwan, should be fixed in `master` branch
