### ISSUE TITLE
Default help won't exict itself

### ISSUE THREAD

**Issue by omidfi** [mattallty/Caporal.js#26]
Hello, 
Thanks for the nice project!

I'm using Caporal for an open source project. Currently, I got a problem: when the app is run by --help 
the help screen won't stop, until I press ctrl x 

Any ideas?

**Comment by mattallty** [comment]
Hello, it may comes from your App, as the `pizza` example exit as expected.
I think you have some listeners set up, so node does not exit. As Caporal cannot guess it, I think I'm gonna add an process.exit() in the help function.

**Comment by mattallty** [comment]
Hi @omidfi, this should be fixed in PR #27

**Comment by omidfi** [comment]
Thanks a lot :)
