### ISSUE TITLE
Completions for arguments not working

### ISSUE THREAD

**Issue by robojones** [mattallty/Caporal.js#28]
I am using corporal for the npm module "z1". It is a module that allows you to easily cluster node-apps.

In my code I am using caporal like this:

![selection_046](https://cloud.githubusercontent.com/assets/21033651/23834026/9f6306c6-074f-11e7-9b5c-2dbb12a48216.png)

This is my completion function:

![selection_047](https://cloud.githubusercontent.com/assets/21033651/23834038/c52f5efe-074f-11e7-940d-76ef13361172.png)

In this example case it returns a promise that resolves to the following array:

```javascript
['exampleApp:/home/jonathan/Desktop/z1/example']
```

Now I am trying to use the completion:

![selection_044](https://cloud.githubusercontent.com/assets/21033651/23834000/1732ac52-074f-11e7-8ebd-a2f845f14900.png)

&lt;tab&gt; &lt;tab&gt;

![selection_043](https://cloud.githubusercontent.com/assets/21033651/23834068/38f10ec8-0750-11e7-9a0d-b14c3682b4b3.png)

The completion for the [appName] argument is not showing up.
I am selecting one of the two options.

&lt;tab&gt; &lt;tab&gt;

![selection_049](https://cloud.githubusercontent.com/assets/21033651/23834095/d76ff690-0750-11e7-948d-f24557b88906.png)

The completion for the [appName] is showing up (last in the list) where it should not.

I am not sure, if I am doing something wrong and it would be nice if you could help me out.
(Here is the complete CLI file https://github.com/robojones/z1/blob/caporal/cli/index.js)

**Comment by mattallty** [comment]
Hi @robojones, thank you for the feedback!
Your code seems valid, going to look ASAP.

**Comment by coreyferguson** [comment]
It seems to be an issue with the first argument, specifically.

In this example, auto-completion of `<kind>` works but not `<from-store>`:

```javascript
const prog = require('caporal');

prog
  .version('1.0.0')
  // the "order" command
  .command('order', 'Order a pizza')
  // <kind> will be auto-magicaly autocompleted by providing the user with 3 choices
  .argument('<from-store>', 'Which store to order from')
  // enable auto-completion for <from-store> argument using a sync function returning an array
  .complete(function() {
    return ['store-1', 'store-2', 'store-3', 'store-4', 'store-5'];
  })
  .argument('<kind>', 'Kind of pizza', ["margherita", "hawaiian", "fredo"])
  .action(function(args, options, logger) {
    logger.info("Command 'return' called with:");
    logger.info("arguments: %j", args);
    logger.info("options: %j", options);
  });

prog.parse(process.argv);
```

If you shift the sequence of the arguments the first argument specified will not be auto-completed.

**Comment by coreyferguson** [comment]
This still isn't quite working right for z-shell. Usually when tabbing I can get recommended results and choose the relevant one. But it's not happening here. Seems to be happening on the `comple` callback function.
