### ISSUE TITLE
options not found unless a long option name set

### ISSUE THREAD

**Issue by indieisaconcept** [mattallty/Caporal.js#29]
I've discovered an issue whereby if you do not specify a long name for an option it results in no option being available as part of the options object when the action is called.

Consider the following

```JavaScript

$ deploy -e staging   

// not working

prog.version('1.0.0')
    .command('deploy') // concat files
    .option('-e <environment>', 'deployment environment')
    .action(function(args, options) {
        console.log(args, options); // => {}, {} 
    });

prog.parse(process.argv);

// working

prog.version('1.0.0')
    .command('concat') // concat files
    .option('-e, --env <environment>', 'deployment environment')
    .action(function(args, options) {
        console.log(args, options); // => {}, { env : 'staging' } 
    });
```

You will notice that updating the option to the format of '-e, --env <environment>' makes the option available.

It took me a while to track down the issue, but I believe the offending line which is causing this behaviour is in `./lib/command.js`- [#L315](https://github.com/mattallty/Caporal.js/blob/master/lib/command.js#L315) , where camel case checks are performed. Should there be no long name defined then the option is not available.

Something along the lines of 

```JavaScript
_camelCaseOptions(options) {
  return this._options.reduce((acc, opt) => {

    const keyName = opt.name();

    if (typeof options[opt.getLongCleanName()] !== 'undefined') {
      acc[keyName] = options[opt.getLongCleanName()];
    } else {
      acc[keyName] = options[keyName];
    }
    return acc;
  }, {});
}
```

It wasn't immediately obvious this was the issue. I wonder if this could be addressed by updating the docs or amending the code to accommodate the scenario whereby a short name is only used.

**Comment by mattallty** [comment]
Hi @indieisaconcept, thank you for the bug report. Going to fix it soon.

**Comment by indieisaconcept** [comment]
@mattallty thanks for fixing.
