### ISSUE TITLE
Custom logger could affect the auto-generated help  

### ISSUE THREAD

**Issue by yuhwan** [mattallty/Caporal.js#34]
### background
I'm using [the logdown module](https://github.com/caiogondim/logdown.js) as my custom logger, which is one of winston-compatible loggers. This module provides a functionality to attach a tiny emoji and a custom prefix to every messages like below.
```javascript
const logger = require('logdown')('caporal:');
logger.info('this is a test message');
```
```
ℹ caporal: this is a test message
```
### problem
The problem is the custom logger attaches the meta data(i.e., emoji and prefix) into the **help** instructions as well. This is because the help.js utilizes [program.logger object](https://github.com/mattallty/Caporal.js/blob/master/lib/help.js#L31) to print out the help instructions. So, when I set my custom logger, the help instructions are like below.
```
ℹ caporal: 
   caporal test 1.0.0 
     
   USAGE
```

### solution idea
The logdown logger may be not the only one that has this problem. I think the help instruction message should be independent with custom logger because it's auto-generated by Caporal.js. How about just using the default console.log function to print out the help instructions? 

Please let me know there is any point that I misunderstood or missed 👍

**Comment by mattallty** [comment]
Thanks for your feedback, I agree with your analysis and solution
