### ISSUE TITLE
_validateWithFlags breaks prog.LIST

### ISSUE THREAD

**Issue by indieisaconcept** [mattallty/Caporal.js#39]
@mattallty I was intending to use prog.LIST and was reviewing the pizza example and found that I was not getting the expected result.

Consider the following

```
-add-ingredients=a,b => { addIngredients : undefined }
-add-ingredients a,b => { addIngredients : [undefined, undefined }
```
I reviewed the code and the issue appears to be caused by [_validateWithFlags](https://github.com/mattallty/Caporal.js/blob/master/lib/validator.js#L92) and an omission of an early return statement when running in unary mode.

As the function calls itself for each value in the Array it will not pass the subsequent validation checks.

```
 _validateWithFlags(value, unary) {
    if (unary) { return value; } 
    ....
}
```

Though value.map and calling itself seems be redundant.

**Comment by mattallty** [comment]
Thanks @indieisaconcept , PR #43 should fix this

**Comment by indieisaconcept** [comment]
@mattallty awesome, thanks!
