### ISSUE TITLE
Default command

### ISSUE THREAD

**Issue by leohahn** [mattallty/Caporal.js#44]
Hey, is it possible to add a default command? I did not find this mentioned on the documentation.

**Comment by mattallty** [comment]
By omitting the .command() call, a default command si created behind the scene. This command will be executed when no known command is passed in the command line. However this command has no name.  I don't thing this is that you want, I think what you would prefer is tagging a known command, as the default when no command is passed, which is a bit different.

**Comment by leohahn** [comment]
Yeah, I tried aliasing an existing command with an empty string, but that did not work.

**Comment by mattallty** [comment]
Just merged in master: #57 , hope this will fit your needs.
