### ISSUE TITLE
Hard coded process argument

### ISSUE THREAD

**Issue by yelgulwa** [mattallty/Caporal.js#46]
There is a reference to a hardcoded process argument in lib/program.js https://github.com/mattallty/Caporal.js/blob/master/lib/program.js#L24 This breaks our Electron application which does not contain a second argument when built. This property is not being used anywhere else in the code. In general, a library should not reference a hard coded value like that and should have sanity checks. Could you please fix that?

I've created a PR https://github.com/mattallty/Caporal.js/pull/45 but it does not pass the tests.

Thanks

**Comment by mattallty** [comment]
Thank you for your report, this has been fixed in #75.
