### ISSUE TITLE
Option validator - function

### ISSUE THREAD

**Issue by nlemoine** [mattallty/Caporal.js#51]
[This example](https://github.com/mattallty/Caporal.js#function-validator) suggests the error message (`throw new Error("You can only order margherita or hawaiian pizza!");`) is returned when an error occurs. But I always get this message `Error: Invalid value 'some option' for option --file.` when I throw an error. 

Is this a bug or the intended behavior?

Thanks for your feedback!

**Comment by mattallty** [comment]
Yes you're right, and the documentation is wrong ;-)
Indeed, you can throw any Error you want, the error message printed to the user will be the same.

**Comment by boneskull** [comment]
Wait, so this *is* intended behavior?   I'd like to be able to tell a user *why* their input was incorrect.

**Comment by cazgp** [comment]
I'd also like to tell the user why their input was incorrect.
