### ISSUE TITLE
Adding a default command removes all commands from auto-generated help

### ISSUE THREAD

**Issue by omidfi** [mattallty/Caporal.js#52]
Hi, 
After updating to Caporal 0.5.0, the commands in my help are missing. 

If I remove the default command, by removing .action from the below snippet, all the commands appear again in help:

```javascript
prog
  // default command
  .version(VERSION)
  .action(commands.nextUndoneAction)
  .description(COMMAND_DESCRIPTIONS.default)
```

I'm talking about Moro, and here's the link to that part of code: [link to repo](https://github.com/omidfi/moro/blob/master/bin/moro.js#L48)

**What I expect?**
All the commands appear in help
**What I get?**
No help for specific commands is listed in help. 

Might be related to #47 and #44

**Comment by mattallty** [comment]
Hi @omidfi thanks for the bug report, will take a look -- in the meantime, if you find the reason, feel free to send a PR

**Comment by fabiospampinato** [comment]
@mattallty are you going to marge the PR or not?

**Comment by ole3021** [comment]
Face the same problem, please fix it
