### ISSUE TITLE
how can I generate routes template

### ISSUE THREAD

**Issue by danieltoro** [mattallty/Caporal.js#59]
example:

    router.get('/${folder}', controller.${folder}.${folder}Find)
    router.get('/${folder}/id/:id', controller.${folder}.${folder}FindById)
    router.post('/${folder}', controller.${folder}.${folder}Create)
    router.put('/${folder}/:id', controller.${folder}.${folder}Update)
    router.delete('/${folder}/:id', controller.${folder}.${folder}Delete)

**Comment by angeliski** [comment]
Hey @danieltoro Can explain your question? I can't understand that.
