### ISSUE TITLE
Sub-commands support

### ISSUE THREAD

**Issue by Szpadel** [mattallty/Caporal.js#62]
Feature request:
It is really helpful to have possibility for creating sub-commands like in many popular tools:

```
$ myprogram category command --options
```

This is especially helpful when your program contains generated list of commands

This would be really nice to be able to embed set of commands inside of other one.

**Comment by mattallty** [comment]
Hi, did you try `prog.command("category command")` ?

**Comment by mattallty** [comment]
Closed as already supported
