### ISSUE TITLE
Support for an "Examples" section

### ISSUE THREAD

**Issue by fabiospampinato** [mattallty/Caporal.js#67]
I use a CLI app that shows an `Examples` section in it's `help` page:

<img width="413" alt="screen shot 2017-08-31 at 19 27 10" src="https://user-images.githubusercontent.com/1812093/29936434-84d9bf9c-8e82-11e7-9422-591072be589f.png">

I think it would be pretty useful to have an `#example` API added to Caporal for showing something similar to this.

What do you think?

**Comment by laudeon** [comment]
Hello,
I agree with @fabiospampinato. This could be a good enhancement!

**Comment by mattallty** [comment]
Hello @fabiospampinato, sorry for the late reply, you should be able to add some help with `program.help(yourGlobalHelpText)` and/or `command.help(yourComandHelpText)`. These help texte will be added in a *MORE INFO* section right after the *Options* section.

**Comment by mattallty** [comment]
Hi @fabiospampinato, I like your suggestions, would be happy to review a PR if you have some time for it, otherwise I will try to take a look at it ASAP, thanks !

**Comment by fabiospampinato** [comment]
I'll be happy to make a PR, give me a few days to find the time :)
