### ISSUE TITLE
Simple example is not working

### ISSUE THREAD

**Issue by ihorskyi** [mattallty/Caporal.js#7]
Running this example on node v7.6.0 gives no output at all

https://github.com/mattallty/Caporal.js#simple-program-single-command

**Comment by mattallty** [comment]
Hi @ihorskyi, thanks for the report. This is a typo error, you always have to call `prog.parse(process.argv);` to make Caporal "run".

So the right example would be:

```
#!/usr/bin/env node
const prog = require('caporal');
prog
  .version('1.0.0')
  .description('A simple program that says "biiiip"')
  .action(function(args, options, logger) {
    logger.info("biiiip")
  });

prog.parse(process.argv);
```

I'm going to fix the docs.

**Comment by mattallty** [comment]
Docs fixed in master branch, closing the issue, thank you for the feedback @ihorskyi !
