### ISSUE TITLE
--no-color and --no-colors do not work (but --color=false does)

### ISSUE THREAD

**Issue by codyzu** [mattallty/Caporal.js#73]
I was experimenting with your framework today (I like the built in logger stuff).

The [README](https://github.com/mattallty/Caporal.js#colors) says I can deactivate the colors with `--no-colors`. The _global options_ added to the help message by the framework say `--no-color`. Neither work and both result in an error :-(

Browsing the source and experimenting, revealed the magic option is `--color=false`.

Just thought I should point out that the README and the generated help are incorrect.

I like your framework. Nice work!

**Comment by mattallty** [comment]
Hi @codyzu, thank you for the report, I've just pushed `fix-no-colors`branch if you want to test it.
