### ISSUE TITLE
Variables with equal symbol

### ISSUE THREAD

**Issue by ddimitrioglo** [mattallty/Caporal.js#81]
I'm trying to pass as variable something like `--params="var1=val1, var2=val2"` and receiving just `var1` as result.
Is there some workaround or proper config?

**Comment by ddimitrioglo** [comment]
any updates here?

**Comment by mattallty** [comment]
Hi, yes this is due to the parser I'm using, I've to dig it in order to fix it or to use another parser. If you wish, feel free to submit a PR. Thanks!

**Comment by ddimitrioglo** [comment]
As a workaround, I'm using following approach:

```
/**
 * @param {Array} opts
 * @returns {Object}
 */
function optionsToObject(opts) {
  let result = {};

  opts.map(key => key.trim()).forEach(item => {
    let [ property, value ] = item.split(':');
    let lowerCaseValue = value.trim().toLowerCase();

    result[property.trim()] = ['true', 'false'].includes(lowerCaseValue) ? (lowerCaseValue === 'true') : value.trim();
  });

  return result;
}
```

and this function converts `"var1:val1, var2:val2, val3:true"` into `{var1: "val1", var2: "val2", val3: true}`

if this is acceptable from your point of view I can try to figure out how to inject this parser into your project.

**Comment by mattallty** [comment]
This is unfortunately too specific for having it included in caporal. Closing for now, but will think about a way of letting users extending the parser to achieve this kind of use case.

**Comment by thommeo** [comment]
The use case is when the value of an argument is a some kind of a filter

```
---filter="field1=val1 & field2=val2"
```

Does it makes sense to reopen the issue?
