### ISSUE TITLE
Accept dot notation

### ISSUE THREAD

**Issue by pvdlg** [mattallty/Caporal.js#83]
Would you consider adding dot notation support? (See [yargs example](http://yargs.js.org/docs/#api-coercekey-fn)).

It would works as follow:
```
myprog --user.name Batman
// options = {user: {name: 'Batman'}}
```

Currently it's possible to defined the option `user.name` and then parse it later. But that forces us to define of the possible "suboption" otherwise we get `Error: Unknown option --user.name.`
In many cases this time of notation is used to generate and options passed to a third-party module for which the possible options are not necessarily know or can numerous. Therefore it's not always possible or a good idea to list all the potential suboption and print them in the help.

Maybe we could allow to do something like this:
```
prog
  .option('--user <user>', 'User options', prog.DOT)
```
The help would look like this:
```
OPTIONS
   --user <user>                    User options
```

Optionally the user could use a custom transform in place of `prog.DOT` that would validate which suboption are allowed.

If all that is too complex or out of scope maybe we could just add an option to not return the `Error: Unknown option --user.name.` when the option `user` has been defined. Basically if `user` option is defined with some sort of "accept dot notation" flag, then accept any `user.*` options. And it would be up to the user to transform/validate in the `action`.

**Comment by mattallty** [comment]
Hi, thanks for the idea, could be useful indeed, behind a flag as you suggest in order to preserve backward compatibility. Open for a PR if you feel like developing it.
