### ISSUE TITLE
The typescript types are wrong with the latest version of Typescript

### ISSUE THREAD

**Issue by cazgp** [mattallty/Caporal.js#91]
Failing program:

```
import * as program from 'caporal'
program.version('0.1.0').name('yarn run make')
```

Property version does not exist on type 'typeof 'caporal''

Type-casting to `any` and it works.

Successful program (when it shouldn't be):

```
import program from 'caporal'
program.version('0.1.0').name('yarn run make')
```

The compiled code fails with TypeError: Cannot read property 'version' of undefined

**Comment by sandangel** [comment]
you can work around like this

```typescript
import * as caporal from 'caporal';

const program = caporal as any;

(program as Caporal)
```
