### ISSUE TITLE
Argument flag order seems to be important

### ISSUE THREAD

**Issue by cazgp** [mattallty/Caporal.js#93]
There is different behaviour between:

`./program language -e name` and `./program language name -e` when program is defined as:

```
    program
        .command('language', 'create a language')
        .argument('[name]', 'name of the language', validateLanguageName)
        .option('-e --errorOnChange', 'error if the language file has changed')
        .action(createLanguage)
```

In the first case, `name` is never set and is sent to `createLanguage` as undefined. The validation function is never called either.
In the second case, `name` is set as expected.

Is this a feature or a bug? It seems to work against other CLIs which can take flags in any order.

**Comment by mattallty** [comment]
Hi, Did you try with a boolean validator ? Closing this issue as it is obviously a bit old

**Comment by cazgp** [comment]
I think it's fantastic that you build tools in your free time for other people to use, and I really respect that. However, I do think it's a bit unfair to close a ticket as "old" when it was never acknowledged or addressed, especially when the suggestion doesn't seem to have that much to do with the initial bug. Since this issue was never responded to, I ended up using a different CLI library, which is a shame because this one seemed so promising.

**Comment by mattallty** [comment]
My bad, did a lot of cleansing yesterday, and by quickly reading this 1 year issue, I thought this was outdated. Still, I added a suggestion regarding boolean validator (for your `-e, --errorOnChange`).
If you think its a bug (I didn't test), please reply in the issue and I will give a closer look now that v1.0 has been released. Best thing to help me would me to submit a PR with a test file showing the bug. Best

**Comment by cazgp** [comment]
It's no problem, thanks for being so gracious.

I can't promise that I'll have time to do that, but I will try at some point over the next few weeks if I remember!
