### ISSUE TITLE
Got a plan to get global options in sub command?

### ISSUE THREAD

**Issue by axetroy** [mattallty/Caporal.js#96]

**Comment by tjbenton** [comment]
Here's a workaround to add all the default args to every sub command.

```js
const default_cmd = program._commands[0]
for (const cmd of program._commands.slice(1)) {
  cmd._options.unshift(...default_cmd._options)
}
```

I would like to see this added to the project as well. In addition I think it would be nice to have it in a different section. That way when someone looks at the sub command help they can see the options that are specific to the sub command as well as the global options that you defined on the root.

**Comment by mattallty** [comment]
Nice hack @tjbenton - going to close this as this does not seem to be a must-have feature
